### ISSUE TITLE
Group rolling doesn't work for damage and type

### ISSUE THREAD

**Issue by AlexanderMee** [caewok/fvtt-action-initiative#10]
When using weapon damage or weapon type settings, when rolling multiple NPCs, the prompt to choose npcs and weapon comes up but clicking roll does nothing.

**Comment by AlexanderMee** [comment]
Correction: it appears to work sometimes. I think the issue is to do with not finding the weapon on the NPC sheet. 
One work around is to use Other Action and type in the formula for the weapon. It's a little annoying but still quicker than rolling multiple times.

**Comment by caewok** [comment]
Should be addressed in v0.3.0.
