### ISSUE TITLE
Basic Variant menu missing text

### ISSUE THREAD

**Issue by AlexanderMee** [caewok/fvtt-action-initiative#11]
<img width="495" alt="image" src="https://github.com/caewok/fvtt-action-initiative/assets/15934269/7f7ba4c7-f21b-4c9a-b42f-1176f959ef38">

The basic variant menu is missing the names of the actions that go with each dice formula.

**Comment by caewok** [comment]
That is odd; I don't see that in my version. What version Foundry, system, and Action Initiative Module are you using?

**Comment by caewok** [comment]
Closing as not replicable. Try v0.3.0 and feel free to open a new issue if it persists.
