### ISSUE TITLE
Initiative button does nothing when clicked, error in log

### ISSUE THREAD

**Issue by AlexanderMee** [caewok/fvtt-action-initiative#12]
Action Initiative and lib-wrapper are my only installed modules

<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/actioninitiative/scripts/Combat.js:52" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">Combat.js:52</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: undefined. game.combat.getCombatantsByToken is not a function
[Detected 3 packages: actioninitiative(0.2.0), lib-wrapper(1.12.15.0), system:dnd5e(3.2.1)]
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/actioninitiative/scripts/Combat.js:52:36" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">Combat.js:52:36</span>
</span>    at Array.forEach (&lt;anonymous&gt;)
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Combat5e.rollInitiative (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/actioninitiative/scripts/Combat.js:50:10" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">Combat.js:50:10</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at 🎁Combat.prototype.rollInitiative#0 (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/lib-wrapper/src/lib/libWrapper-wrapper.js:187:52" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">libWrapper-wrapper.js:187:52</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Actor5e.rollInitiative (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/scripts/foundry.js:18988:18" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">foundry.js:18988:18</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async Actor5e.rollInitiative (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/systems/dnd5e/module/documents/actor/actor.mjs:1913:20" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">actor.mjs:1913:20</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async Actor5e.rollInitiativeDialog (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:30000/modules/actioninitiative/scripts/Actor5e.js:36:3" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">Actor5e.js:36:3</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | (anonymous) | @ | Combat.js:52
-- | -- | -- | --
  | rollInitiative | @ | Combat.js:50
  | 🎁Combat.prototype.rollInitiative#0 | @ | libWrapper-wrapper.js:187
  | rollInitiative | @ | foundry.js:18988

</span></div>
</body>
</html>

**Comment by caewok** [comment]
What Foundry version and system version are you running?

**Comment by caewok** [comment]
Closing as not replicable with the refactor in v0.3.0.
