### ISSUE TITLE
"All Combatants" checkbox request

### ISSUE THREAD

**Issue by Giannatosp** [caewok/fvtt-action-initiative#2]
Your module has helped me so much in our AD&D 2e games! I could not roll initiative without it!. A great time-saver would be if there was an extra checkbox somewhere in the "Roll multiple" initiative dialigues, that selected all combatants. Now, I have to click manually on all of them each round. Could this be implemented?
![image](https://github.com/caewok/fvtt-action-initiative/assets/100585525/7488d45d-52f4-47a6-b31e-96cef61d6388)

**Comment by caewok** [comment]
Thanks! Added in v0.1.1. You will also see that the filters are responsive now—if you select/deselect a combatant, the associated filters will be updated accordingly.
