### ISSUE TITLE
localize ( lookup ( concat...

### ISSUE THREAD

**Issue by ingodjan** [caewok/fvtt-action-initiative#4]
Hey, sorry to bother!

First is all, thanks for creat this module. Very useful!

I'm trying to use it, but by some reason, the actions names in the combatants dialog is empty. HandleBars' lookup is resolving undefined, resulting in empty string, and I'm wondering if you have any insights of why.

Thanks in advance!

**Comment by DreamyNiri** [comment]
Adding to this to hopefuly get a response

**Comment by DreamyNiri** [comment]
changing line 40 in combatant.html to `<label> {{ localize (concat "actioninitiative.phrases." this) }} </label>` worked

**Comment by caewok** [comment]
Thanks! Should be incorporated into v0.1.2.
