### ISSUE TITLE
Rolling incorrectly.

### ISSUE THREAD

**Issue by CyantoIogy** [caewok/fvtt-action-initiative#6]
Got the newest update for DnD5E, and it's rolling a d20 instead of the alternative dice. The interface is working, and it's showing the text for the check boxes, but it's rolling initiative normally (d20+dex).

**Comment by caewok** [comment]
Sorry, I must have broken something. I had it working but then apparently broke something later... will look into it.

**Comment by caewok** [comment]
Well, it actually was a change in dnd5e v3.1. Which explains why I didn't see it! I had done some testing in v3 but did not notice the rolling fails in the v3.1 update. Hopefully fixed in the v0.1.3 update, just released. Thanks!
